### PR TITLE
[SPARK-25299] Introduce the new shuffle writer API

### PR DESCRIPTION
**Pull request by ifilonenko**
## What changes were proposed in this pull request?

Introduced the new shuffle writer API and all dependent APIs: ShuffleDataIO, ShuffleExecutorComponents (executor-side shuffle plugin), writer APIs, for output streams only.

## How was this patch tested?

Compiled

### CODE REVIEW

**Comment by ifilonenko** [comment]
@mccheah good for merge?

**Review by mccheah — COMMENTED** [review]
Looks fine to me

**Comment by mccheah** [comment]
Actually it's not, haha. Sorry. I noticed that everything is indented with 4 spaces, but Spark's standard is to indent even Java with 2 spaces. Can that be fixed?

**Comment by ifilonenko** [comment]
yes, this has been updated. Good to merge?

**Comment by mccheah** [comment]
Yup, we can merge this and we'll add it to our branch. For this workflow for now, we'll follow up if the build breaks in CircleCI as well.

**Pull request merged**
